branches:
  except: /^v\d/
language: node_js
node_js: node
matrix:
  include:
  - script: eval xvfb-run `jq --raw-output .scripts.test < package.json`
  - os: osx
    osx_image: xcode9.3beta
branches:
  except: /^v\d/
