if: branch !~ ^v\d
language: node_js
node_js: node
jobs:
  include:
    - dist: xenial
      script: eval xvfb-run `jq --raw-output .scripts.test < package.json`
    - dist: xenial
      script: nyc node lib/find-pkg-dir/test.js
    - os: osx
      osx_image: xcode10.2
    - os: windows
      script: node lib/find-pkg-dir/test.js
    - dist: xenial
      script: node server/test/test.js
    - os: windows
      script: node server\\test\\test.js

notifications:
  email: false
